### ISSUE TITLE
time_translator多余了？

### ISSUE THREAD

**Issue by crazygit** [liuour/rime#15]
```yaml
# librime-lua 输入动态时间和日期
  "engine/translators/@6": lua_translator@date_translator
  "engine/translators/@7": lua_translator@time_translator
```

感觉这里多余了 ~~` "engine/translators/@7": lua_translator@time_translator`~~
